In [1]:
import pandas as pd
data = pd.read_csv("/home/user/Desktop/Muturi_AI/Muturri_ML/datasets/Groceries_dataset.csv")
data

       Member_number        Date        itemDescription
0               1808  21-07-2015         tropical fruit
1               2552  05-01-2015             whole milk
2               2300  19-09-2015              pip fruit
3               1187  12-12-2015       other vegetables
4               3037  01-02-2015             whole milk
...              ...         ...                    ...
38760           4471  08-10-2014          sliced cheese
38761           2022  23-02-2014                  candy
38762           1097  16-04-2014               cake bar
38763           1510  03-12-2014  fruit/vegetable juice
38764           1521  26-12-2014               cat food

[38765 rows x 3 columns]

In [2]:
data.groupby("Member_number").size()

Member_number
1000    13
1001    12
1002     8
1003     8
1004    21
        ..
4996    10
4997     6
4998     2
4999    16
5000     7
Length: 3898, dtype: int64

In [3]:
data.groupby("Date").size()

Date
01-01-2014    48
01-01-2015    48
01-02-2014    62
01-02-2015    61
01-03-2014    54
              ..
31-07-2015    63
31-08-2014    47
31-08-2015    47
31-10-2014    57
31-10-2015    46
Length: 728, dtype: int64

In [4]:
data.groupby("itemDescription").size()

itemDescription
Instant food products      60
UHT-milk                  323
abrasive cleaner           22
artif. sweetener           29
baby cosmetics              3
                         ...
white bread               362
white wine                176
whole milk               2502
yogurt                   1334
zwieback                   60
Length: 167, dtype: int64

In [5]:
data.isnull().sum()

Member_number      0
Date               0
itemDescription    0
dtype: int64

In [6]:
data.groupby(['Member_number', 'Date']) ['itemDescription'].sum()

Member_number  Date
1000           15-03-2015           sausagewhole milksemi-finished breadyogurt
               24-06-2014                          whole milkpastrysalty snack
               24-07-2015                           canned beermisc. beverages
               25-11-2015                              sausagehygiene articles
               27-05-2015                               sodapickled vegetables
                                                   ...
4999           24-01-2015    tropical fruitberriesother vegetablesyogurtkit...
               26-12-2015                                   bottled waterherbs
5000           09-03-2014                          fruit/vegetable juiceonions
               10-02-2015               sodaroot vegetablessemi-finished bread
               16-11-2014                         bottled beerother vegetables
Name: itemDescription, Length: 14963, dtype: object

In [7]:
# pivot table is a way to reshape and summarize the data
# create baskets
baskets = data.pivot_table(index="Member_number", columns="itemDescription", aggfunc='size', fill_value=0)
baskets

itemDescription,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
Member_number,,,,,,,,,,,,,,,,,,,,,
1000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,1,0
1001,0,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,1,0,2,0,0
1002,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1003,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1004,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
4998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4999,0,0,0,0,0,0,0,0,0,2,...,0,0,0,1,0,0,0,0,1,0
5000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
# CReate an encode function to encode the pivot table
# This is basically yes or no answer to whether a production was purchased or not in a transaction
# in other words, it is whther a product exists in an itemset of a transaction or not
# if yes, we replace with 1 and other we have 0

def encode(x):
    # x is the quantity as shown on the pivot
    if x<=0:
        return 0
    if x > 0:
        return 1
    
# we shall then apply the above encoding function to the baskets
baskets_sets = baskets.applymap(encode)
baskets_sets

/tmp/ipykernel_9269/1147395143.py:14: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  baskets_sets = baskets.applymap(encode)

itemDescription,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
Member_number,,,,,,,,,,,,,,,,,,,,,
1000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
1001,0,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,1,0,1,0,0
1002,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1003,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1004,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
4998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4999,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,1,0
5000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0